databases:
  - name: ums-db
    databaseName: ums
    user: ums
    plan: free

services:
  - type: web
    name: ums
    plan: free
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ums_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ums-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
